version: '2'
services:
  base:
    build: .
    env_file:
      - .docker.env

  waiter:
    extends: base
    command: node waiter/index.js
    ports:
      - 3001:3001
    links:
      - mongodb
      - rabbit

  cook:
    extends: base
    command: node cook/index.js
    ports:
      - 3002:3002
    links:
      - mongodb
      - rabbit

  customer:
    extends: base
    command: node customer/index.js
    ports:
      - 3000:3000
    links:
      - waiter

  mongodb:
    image: mongo:4.0
    restart: always
    ports:
      - 27017:27017

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - 15672:15672
      - 5672:5672

  
